import { spawn } from "node:child_process";
import { mkdirSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const index = process.argv.indexOf("--out");
if (index < 0 || !process.argv[index + 1]) throw new Error("--out required");
const out = resolve(process.argv[index + 1]);
if (existsSync(out)) throw new Error("Use a new output directory; prior evidence is preserved");
mkdirSync(out, { recursive: true });
const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
const child = spawn(require("electron"), [resolve("scripts/desktop/security-fixture.cjs"), `--fixture-out=${out}`], { env, windowsHide: true, stdio: ["ignore", "pipe", "pipe"] });
let stdout = "", stderr = "";
child.stdout.on("data", (chunk) => { stdout += chunk; });
child.stderr.on("data", (chunk) => { stderr += chunk; });
const timeout = setTimeout(() => { child.kill(); }, 30000);
const code = await new Promise((done, reject) => { child.once("error", reject); child.once("exit", done); });
clearTimeout(timeout);
writeFileSync(resolve(out, "process.json"), JSON.stringify({ code, stdout, stderr }, null, 2));
const report = existsSync(resolve(out, "report.json")) ? JSON.parse(readFileSync(resolve(out, "report.json"), "utf8")) : null;
console.log(JSON.stringify({ code, report }, null, 2));
process.exitCode = code === 0 && report?.passed === true ? 0 : 1;
